### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by stemcc** [centricular/gstcefsrc#41]
I'm using a Wayland-only build of gstreamer inside a docker container, and currently using wpesrc for bringing in web content. I'd love to include this element in my build as well, but would rather avoid bringing in x11 if I can. 

I'm curious if Wayland support is on the roadmap or what blockers might be in the way of Wayland support. 

For reference: https://www.collabora.com/news-and-blog/blog/2019/05/08/cef-on-wayland-upstreamed/

**Comment by MathieuDuponchelle** [comment]
Hey @stemcc :) No one that I know of is actively working on new features for this element at the moment, I'll be happy to merge in any patches that might be needed to help with wayland support of course. Nothing in the element code directly depends on X11, and it might just be a matter of testing against a `use_ozone=true` chromium build.

Note that building chromium manually is a bit of a time-consuming process, and I've mostly relied on testing against the spotify builds (https://cef-builds.spotifycdn.com/index.html). I do not know if those are built with this flag, needs checking :) Then I notice in collabora's blog post that the cef_simple example requires a `--ozone-platform=wayland` command line switch, perhaps the element would need a property implementing a similar behavior?

I will close this issue because it has no immediately addressable item, please don't take this to mean I'm not interested, if you come up with a Merge Request I'll happily review it!

**Comment by SteveMcFarlin** [comment]
@stemcc Is your Wayland only build using wpesrc able to composite on a GPU? I am having a lot of difficulty getting cefsrc/cef to composite offscreen in X11.
